USE [SIGANEM]
GO

/* GARANTIAS VALOR */

ALTER TABLE [dbo].[GARANTIAS_VALORES] ADD Monto_Valor_Mercado_Colonizado NUMERIC(22, 2) NULL
GO


/* GRADOS_PRIORIDADES */

ALTER TABLE [dbo].[GRADOS_PRIORIDADES] ADD Saldo_Prioridad_Colonizado DECIMAL(22, 2) NULL
GO