USE [SIGANEM]
GO

/* TEMPORAL GARANTIAS: ACTUALIZACION DE MONTOS CALCULADOS */

ALTER TABLE [dbo].[AUX_ACTUALIZAGARANTIAS] ADD Monto_Ultima_Tasacion_No_Terreno NUMERIC(22, 2) NULL
GO


/*SE ELIMINAN LAS TABLAS TEMPORALES DE LOS ESCENARIOS DEL CALCULO DEL PORCENTAJE DE RESPONSABILIDAD*/
IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_A') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_A

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_A') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_A



IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_B') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_B

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_B') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_B

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_B_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_B_1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_B_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_B_1



IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_C1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_C1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C1

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_C1_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_C1_1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C1_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C1_1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C1_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C1_2

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C1_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C1_3
	
IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C1_4') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C1_4

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_C2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_C2

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C2

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_C2_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_C2_1

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_C2_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_C2_2

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_C2_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_C2_3

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C2_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C2_1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C2_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C2_2

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C2_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C2_3

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_C2_4') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_C2_4



IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D1

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1_1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D1_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D1_1

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1_2

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1_3

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1_4') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1_4

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D1_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D1_2

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1_5') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1_5

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D1_6') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D1_6

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D1_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D1_3

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D1_4') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D1_4

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D2

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D2_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D2_1

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2_1') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2_1

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D2_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D2_2

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2_2') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2_2

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2_3

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2_4') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2_4

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D2_3') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D2_3

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2_5') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2_5

IF(OBJECT_ID('dbo.AUX_PCJ_GARANTIAS_D2_6') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_GARANTIAS_D2_6

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D2_4') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D2_4

IF(OBJECT_ID('dbo.AUX_PCJ_OPERACIONES_D2_5') IS NOT NULL)
	DROP TABLE dbo.AUX_PCJ_OPERACIONES_D2_5






