USE [USSIGANEM]
GO


/*PERMISOS TABLAS*/

GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_VALORES TO RAP_AccesoUSSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GRADOS_PRIORIDADES TO RAP_AccesoUSSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMETIDAS TO RAP_AccesoUSSIGANEM
GO


/*PERMISOS SPs */

GRANT EXECUTE ON Calculo_Montos_Prioridades_Colonizado TO RAP_AccesoUSSIGANEM
GO
GRANT EXECUTE ON Calculo_Valor_Mercado_Colonizado TO RAP_AccesoUSSIGANEM
GO
GRANT EXECUTE ON Calculo_Actualiza_Valor_Nominal TO RAP_AccesoUSSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Aceptacion_Terreno_SUGEF_Fideicometida TO RAP_AccesoUSSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Aceptacion_No_Terreno_SUGEF_Fideicometida TO RAP_AccesoUSSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Mitigador_Calculado_Fideicometido TO RAP_AccesoUSSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Mitigador_Calculado TO RAP_AccesoUSSIGANEM
GO
