USE [USSIGANEM]
GO


/*PERMISOS TABLAS*/

GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ACCIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ACTIVOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ADMINISTRACIONES_CONTENIDOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.APLICABLES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ARCHIVOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_ACTUALIZAGARANTIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_CATEGORIA TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_CONSULTA_RUC TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_CONSULTA_SALDOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_MONTO_MITIGADOR TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_MTO_ACT_NO_TERRENO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_MTO_ACT_TERRENO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_PRC_ACP_NO_TERRENO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_PRC_ACP_NO_TERRENO_R TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_PRC_ACP_TERRENO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_GAR_PRC_ACP_TERRENO_R TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_A TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_B TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_B_1 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_C TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_C_1 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D_1 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D_2 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D_3 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D_4 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D_5 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_GARANTIAS_D_6 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_A TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_B TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_B_1 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_C TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_C_1 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_C_2 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_C_3 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_C_4 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_D TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_D_1 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_D_2 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PCJ_OPERACIONES_D_3 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_SALDOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_VALORAR TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BITACORAS_PROCESOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.bsmcl TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CAJAS_BREAKERS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CALIFICACIONES_EMPRESAS_CALIFICADORAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CANALIZACIONES_ELECTRICAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CANOAS_BAJANTES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CANTIDADES_FINCAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CANTONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CARACTERISTICAS_TASADORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CATEGORIAS_CALIFICACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CATEGORIAS_CALIFICACIONES_TIPOS_MITIGADORES_RIESGOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CATEGORIAS_RIESGO_DEUDORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CATEGORIAS_RIESGOS_EMPRESAS_CALIFICADORAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CERRAJERIAS_PIEZAS_SANITARIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CIELOS_RASOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CLASES_AERONAVES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CLASES_BUQUES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CLASES_GARANTIAS_PRT_17 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CLASES_TIPOS_BIENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CLASES_TIPOS_BIENES_CLASES_GARANTIAS_PRT_17 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CLASES_VEHICULOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CODIGOS_DUPLICADOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CODIGOS_HORIZONTALIDADES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.COLINDANTES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUBIERTAS_TECHOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DECISIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DELIMITACIONES_LINDEROS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DERECHOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DISTRIBUCIONES_ZONAS_TASADORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DISTRITOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EMISIONES_INSTRUMENTOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EMISORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EMPRESAS_CALIFICADORAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENCHAPES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENFOQUES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENTIDADES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENTREPISOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESCALERAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTADOS_AVALUOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTADOS_CONSTRUCCIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTADOS_GARANTIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTADOS_INSTALACIONES_ELECTRICAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTADOS_PROCESOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTRUCTURAS_TECHOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.FISCALIZADORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.FORMAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_AVALES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDUCIARIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_OPERACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_CEDULAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_INSCRIPCIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_MOBILIARIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_POLIZAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_TASADORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_VALORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GRADOS_GRAVAMENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GRAVAMENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GRUPOS_FINANCIEROS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GRUPOS_RIESGOS_DEUDORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.HML_EMISORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.HML_TIPOS_PERSONAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.INDICACIONES_AJUSTES_AREAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.INDICADORES_GENERADORES_DIVISAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.INDICADORES_MONEDAS_EXTRANJERAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.INDICES_PRECIOS_CONSUMIDOR TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.INSTRUMENTOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.INTERRUPTORES_INSTALACIONES_ELECTRICAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LOTES_SEGREGADOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MATERIALES_CONSTRUCCIONES_PREDOMINANTES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MATERIALES_EXTERNOS_INTERNOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MATERIALES_EXTERNOS_TAPICHELES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MATERIALES_PISOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MATERIALES_PUERTAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MATERIALES_VIAS_ACCESO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MENSAJES_SISTEMAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MODULOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MONEDAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NIVELES_SOCIOECONOMICOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NIVELES_TERRENO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NOTARIOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.NUMEROS_LINEAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ORIENTACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PANTALLAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PANTALLAS_ROLES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PARAMETROS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PARAMETROS_BIENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PENDIENTES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PINTURAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PLANES_INVERSIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PLAZOS_CALIFICACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.POLIZAS_TIPOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.prmca TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.prmcp TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.prmoc TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PROCESOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PROVINCIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PUNTOS_REFERENCIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.RANGOS_PERIODOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.REGIMENES_FISCALIZACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.REPORTES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.REPORTES_ROLES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.REPORTES_SEGUI TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SECCIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SIEF_DEUDOR TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SISTEMAS_CONSTRUCTIVOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SITUACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SOLICITANTES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TASADORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TEMP_DEUDOR_AUTO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TEMP_prmcp TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TENENCIAS_PRT_15 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TENENCIAS_PRT_17 TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ADJUDICACIONES_BIENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ALMACENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ASIGNACIONES_CALIFICACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_AVALES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_AVALES_FIANZAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_BIENES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_CAMBIOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_CAPACIDADES_PAGO TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_CARTERAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_CASOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_CLASIFICACIONES_INSTRUMENTOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_COMPORTAMIENTOS_PAGOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_CONSTRUCCIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_DOCUMENTOS_LEGALES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_EMISORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ENTIDADES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ESTADOS_AVALUOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_GARANTIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_GRADOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_GRUPOS_FINANCIEROS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_IDENTIFICACIONES_RUC TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_INDICADORES_INSCRIPCIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_INGRESOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_INMUEBLES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_INSTRUMENTOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_LIQUIDEZ TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_MENSAJES_SISTEMAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_MITIGADORES_RIESGOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_MONEDAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_OPERACIONES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_PERSONAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_POLIZAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ROLES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_SERVICIOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_VALORES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_VALORES_TENENCIAS_TIPOS_INSTRUMENTOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TIPOS_ZONAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TOPOGRAFIAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TRAMAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.UNIDADES TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.USOS_SUELOS_ACTUAL_ENTORNOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.USUARIOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.USUARIOS_HISTORICOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.VENTANAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.VERJAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.VIAS_ACCESOS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.VOLTAJES_INSTALACIONES_ELECTRICAS TO RAP_AccesoSIGANEM
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ZONAS_TASADORES TO RAP_AccesoSIGANEM
GO



/*PERMISOS SPs */

GRANT EXECUTE ON Activos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Activos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Activos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Activos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Activos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Activos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Activos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Actualiza_Categoria_Riesgo TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Actualiza_Saldos_Contratos_Credito TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Actualiza_Saldos_Operaciones_Credito TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Administraciones_Contenidos_Consulta_Controles TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Administraciones_Contenidos_Consulta_Pantalla TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Administraciones_Contenidos_Consulta_Pestana TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Aplicables_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Aplicables_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Aplicables_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Aplicables_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Aplicables_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Aplicables_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Garantias_Fiduciarias_de_Contratos TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Garantias_Fiduciarias_Operaciones TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Garantias_Reales_Contrato TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Garantias_Reales_de_Operaciones TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Garantias_Valores_de_Contratos TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Garantias_Valores_Operaciones TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Archivos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bienes_Valorar_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bienes_Valorar_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bienes_Valorar_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bienes_Valorar_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bienes_Valorar_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bienes_Valorar_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bitacoras_Procesos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bitacoras_Procesos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bitacoras_Procesos_Inicia TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Bitacoras_Procesos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cajas_Breakers_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cajas_Breakers_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cajas_Breakers_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cajas_Breakers_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cajas_Breakers_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cajas_Breakers_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Grado_Gravamen TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Mitigador_Calculado TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Poliza_Colonizado TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Tasacion_Actualizada_No_Terreno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Monto_Tasacion_Actualizada_Terreno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Aceptacion_No_Terreno_SUGEF TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Aceptacion_Terreno_SUGEF TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Responsabilidad_Escenario_A TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Responsabilidad_Escenario_B TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Responsabilidad_Escenario_C TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Porcentaje_Responsabilidad_Escenario_D TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calculo_Saldo_Grado_Gravamen_Colonizado TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Calificacion_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Categoria_Riesgo_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Consulta_Grid TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Calificaciones_Empresas_Calificadoras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canalizaciones_Electricas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canalizaciones_Electricas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canalizaciones_Electricas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canalizaciones_Electricas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canalizaciones_Electricas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canalizaciones_Electricas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canoas_Bajantes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canoas_Bajantes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canoas_Bajantes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canoas_Bajantes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canoas_Bajantes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Canoas_Bajantes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantidades_Fincas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantidades_Fincas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantidades_Fincas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantidades_Fincas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantidades_Fincas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantidades_Fincas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cantones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Consulta_Grid TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Consulta_Grid_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Caracteristicas_Tasadores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Tipos_Mitigadores_Riesgos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Tipos_Mitigadores_Riesgos_Consulta_Grid TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Tipos_Mitigadores_Riesgos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Tipos_Mitigadores_Riesgos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Calificaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgo_Deudores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgo_Deudores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgo_Deudores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgo_Deudores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgo_Deudores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgo_Deudores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Categorias_Riesgos_Empresas_Calificadoras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cerrajerias_Piezas_Sanitarias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cerrajerias_Piezas_Sanitarias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cerrajerias_Piezas_Sanitarias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cerrajerias_Piezas_Sanitarias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cerrajerias_Piezas_Sanitarias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cerrajerias_Piezas_Sanitarias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cielos_Rasos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cielos_Rasos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cielos_Rasos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cielos_Rasos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cielos_Rasos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cielos_Rasos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Aeronaves_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Buques_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Garantias_Prt_17_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Tipos_Bienes_Clases_Garantias_Prt_17_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Tipos_Bienes_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Tipos_Bienes_Lista_CodClase TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Tipos_Bienes_Lista_IdClase TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Lista_Filtrada TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Clases_Vehiculos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Duplicados_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalidades_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Codigos_Horizontalides_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Colindantes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Colindantes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Colindantes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Colindantes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Colindantes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Colindantes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cubiertas_Techos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cubiertas_Techos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cubiertas_Techos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cubiertas_Techos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cubiertas_Techos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Cubiertas_Techos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Decisiones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Decisiones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Decisiones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Decisiones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Decisiones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Decisiones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Delimitaciones_Linderos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Delimitaciones_Linderos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Delimitaciones_Linderos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Delimitaciones_Linderos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Delimitaciones_Linderos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Delimitaciones_Linderos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Derechos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Derechos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Derechos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Derechos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Derechos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Derechos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distribuciones_Zonas_Tasadores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distribuciones_Zonas_Tasadores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distribuciones_Zonas_Tasadores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distribuciones_Zonas_Tasadores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distribuciones_Zonas_Tasadores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distribuciones_Zonas_Tasadores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Distritos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Emisor_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Fecha_Vencimiento_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Instrumento_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_ISIN_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_ISIN_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Moneda_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Serie_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Tipo_Clasificacion_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Tipo_Clasificacion_Premio_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisiones_Instrumentos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Emisores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Calificadoras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Empresas_Tasadoras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enchapes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enchapes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enchapes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enchapes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enchapes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enchapes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enfoques_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enfoques_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enfoques_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enfoques_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enfoques_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Enfoques_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entidades_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entidades_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entidades_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entidades_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entidades_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entidades_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entrepisos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entrepisos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entrepisos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entrepisos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entrepisos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Entrepisos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Escaleras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Escaleras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Escaleras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Escaleras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Escaleras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Escaleras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Avaluos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Avaluos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Avaluos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Avaluos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Avaluos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Avaluos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Construcciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Construcciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Construcciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Construcciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Construcciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Construcciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Garantias_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Garatias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Instalaciones_Electricas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Instalaciones_Electricas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Instalaciones_Electricas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Instalaciones_Electricas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Instalaciones_Electricas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estados_Instalaciones_Electricas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estructuras_Techos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estructuras_Techos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estructuras_Techos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estructuras_Techos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estructuras_Techos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Estructuras_Techos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Fiscalizadores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Fiscalizadores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Fiscalizadores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Fiscalizadores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Fiscalizadores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Fiscalizadores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Formato_Identificacion_Vehiculo_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Avales_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Avales_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Avales_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Avales_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Avales_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Avales_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Fiduciarias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Fiduciarias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Fiduciarias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Fiduciarias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Fiduciarias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Fiduciarias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Consulta_Grid_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Estado_Replica TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Fecha_Prescripcion_Garantia TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Fecha_Vencimiento_Garantia TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Operaciones_Trama TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Actualiza_Generales TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Actualiza_Tipo_Bien TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Consulta_Grid_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Cedulas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Empresas_Tasadoras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Fecha_Vencimiento_Avaluo_SUGEF TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inscripciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inscripciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inscripciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inscripciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inscripciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inscripciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inserta_Generales TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Inserta_Total TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Mobiliarias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Mobiliarias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Mobiliarias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Mobiliarias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Mobiliarias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Mobiliarias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Personas_Tasadoras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Poliza_Trama TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Polizas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Polizas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Polizas_Consulta_Grid_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Polizas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Polizas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Tasadores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Tasadores_Consulta_Grid_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Tasadores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Tasadores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Tasadores_Personas_Tasadoras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Reales_Valida TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Actualiza_Generales TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Consulta_ISIN TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Inserta_Generales TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Trama TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Garantias_Valores_Valida TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grados_Gravamenes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Gravamenes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Gravamenes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Gravamenes_Consulta_Grid_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Gravamenes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Gravamenes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Financieros_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Financieros_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Financieros_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Financieros_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Financieros_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Financieros_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Riesgos_Deudores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Riesgos_Deudores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Riesgos_Deudores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Riesgos_Deudores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Riesgos_Deudores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Grupos_Riesgos_Deudores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Inconsistencias_Garantias_Fiduciarias_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Inconsistencias_Garantias_Fiduciarias_Lista_Eliminado TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicaciones_Ajustes_Areas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicaciones_Ajustes_Areas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicaciones_Ajustes_Areas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicaciones_Ajustes_Areas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicaciones_Ajustes_Areas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicaciones_Ajustes_Areas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Generadores_Divisas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Generadores_Divisas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Generadores_Divisas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Generadores_Divisas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Generadores_Divisas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Generadores_Divisas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indicadores_Monedas_Extranjeras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indices_Precios_Consumidor_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indices_Precios_Consumidor_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indices_Precios_Consumidor_Consulta_BCCR TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indices_Precios_Consumidor_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Indices_Precios_Consumidor_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Inscripcion_Garantia_Operacion_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Inscripcion_Garantia_Operacion_Consulta_DataBridge TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Inscripcion_Garantia_Real_Detalle_Relacion_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Filtrado_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Tipo_Instrumento_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Instrumentos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Interruptores_Instalaciones_Electricas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Interruptores_Instalaciones_Electricas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Interruptores_Instalaciones_Electricas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Interruptores_Instalaciones_Electricas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Interruptores_Instalaciones_Electricas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Interruptores_Instalaciones_Electricas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Lotes_Segregados_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Lotes_Segregados_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Lotes_Segregados_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Lotes_Segregados_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Lotes_Segregados_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Lotes_Segregados_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Construcciones_Predominantes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Construcciones_Predominantes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Construcciones_Predominantes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Construcciones_Predominantes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Construcciones_Predominantes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Construcciones_Predominantes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Internos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Internos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Internos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Internos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Internos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Internos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Tapicheles_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Tapicheles_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Tapicheles_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Tapicheles_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Tapicheles_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Externos_Tapicheles_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Pisos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Pisos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Pisos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Pisos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Pisos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Pisos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Puertas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Puertas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Puertas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Puertas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Puertas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Puertas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Vias_Acceso_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Vias_Acceso_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Vias_Acceso_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Vias_Acceso_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Vias_Acceso_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Materiales_Vias_Acceso_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Mensajes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Mobiliaria_Garantia_Operacion_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Mobiliaria_Garantia_Operacion_Consulta_DataBridge TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Mobiliaria_Garantia_Real_Detalle_Relacion_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Monedas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Socioeconomicos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Socioeconomicos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Socioeconomicos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Socioeconomicos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Socioeconomicos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Socioeconomicos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Terreno_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Terreno_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Terreno_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Terreno_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Terreno_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Niveles_Terreno_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Consulta_Identificacion TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Notarios_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Numeros_Lineas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Numeros_Lineas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Numeros_Lineas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Numeros_Lineas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Numeros_Lineas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Numeros_Lineas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Actualiza_Generales TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Consulta_DataBridge TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Consulta_DataBridge_Auto TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Consulta_RUC TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Consulta_RUC_Auto TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Garantias_Fiduciarias_Busqueda TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Garantias_Reales_Busqueda TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Garantias_Valores_Busqueda TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Inserta_Generales TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Operaciones_Valida TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Orientaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Orientaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Orientaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Orientaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Orientaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Orientaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pantallas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pantallas_Padres_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pantallas_Padres_ConsultaDetalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pantallas_Roles_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pantallas_Roles_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pantallas_Roles_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Parametros_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Parametros_Bienes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Parametros_Bienes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Parametros_Bienes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Parametros_Bienes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Parametros_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pendientes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pendientes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pendientes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pendientes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pendientes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pendientes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pinturas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pinturas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pinturas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pinturas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pinturas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Pinturas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Planes_Inversiones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Planes_Inversiones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Planes_Inversiones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Planes_Inversiones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Planes_Inversiones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Planes_Inversiones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Plazos_Calificaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Polizas_Tipos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Procesos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Provincias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Puntos_Referencias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Puntos_Referencias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Puntos_Referencias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Puntos_Referencias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Puntos_Referencias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Puntos_Referencias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Regimenes_Fiscalizaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Fiduciarias_Especifica_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Fiduciarias_Usuario_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Reales_Cedulas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Reales_Especifica_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Reales_Tasadores TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Reales_Usuario_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Valores_Especifica_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Garantias_Valores_Usuario_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Operaciones_Garantias_Fiduciarias_Replica_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Operaciones_Garantias_Reales_Replica_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reporte_Operaciones_Garantias_Valores_Replica_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Garantias_Fiduciarias_Total TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Roles_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Roles_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Roles_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Roles_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Roles_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_Roles_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_SEGUI_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_SEGUI_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_SEGUI_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_SEGUI_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_SEGUI_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Reportes_SEGUI_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Secciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Secciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Secciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Secciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Secciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Secciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Si_No_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Sistemas_Constructivos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Sistemas_Constructivos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Sistemas_Constructivos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Sistemas_Constructivos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Sistemas_Constructivos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Sistemas_Constructivos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Situaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Situaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Situaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Situaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Situaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Situaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Solicitantes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Solicitantes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Solicitantes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Solicitantes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Solicitantes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Solicitantes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON SP_REPORTE_GARANTIAS_VALORES TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON SP_REPORTE_GARANTIAS_VALORES_ESPEJO TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Consulta_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Tipo_Persona_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tasadores_Total_Filas_Interno TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_15_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tenencias_Prt_17_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Adjudicaciones_Bienes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Adjudicaciones_Bienes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Adjudicaciones_Bienes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Adjudicaciones_Bienes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Adjudicaciones_Bienes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Adjudicaciones_Bienes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Almacenes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Almacenes_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Asignaciones_Calificaciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Fianzas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Avales_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Bienes_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Cambios_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Cambios_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Cambios_Consulta_BCCR TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Cambios_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Cambios_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Capacidades_Pago_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Capacidades_Pago_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Capacidades_Pago_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Capacidades_Pago_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Capacidades_Pago_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Capacidades_Pago_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Carteras_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Carteras_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Carteras_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Carteras_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Carteras_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Carteras_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Casos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Casos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Casos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Casos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Casos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Casos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Clasificaciones_Instrumentos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Comportamientos_Pagos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Comportamientos_Pagos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Comportamientos_Pagos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Comportamientos_Pagos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Comportamientos_Pagos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Comportamientos_Pagos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Construcciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Construcciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Construcciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Construcciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Construcciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Construcciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Documentos_Legales_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Emisores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Emisores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Emisores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Emisores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Emisores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Emisores_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Entidades_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Estados_Avaluos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Garantias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grados_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grados_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grados_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grados_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grados_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grados_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Grupos_Financieros_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_SICC_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Identificaciones_RUC_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inconsistencias_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Indicadores_Inscripciones_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Ingresos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Ingresos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Ingresos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Ingresos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Ingresos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Ingresos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inmuebles_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inmuebles_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inmuebles_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inmuebles_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inmuebles_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Inmuebles_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Instrumentos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Instrumentos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Liquidez_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Mitigadores_Riesgos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Filtrado_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Monedas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Operaciones_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Lista_1_2_3 TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Personas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Polizas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Polizas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Polizas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Polizas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Polizas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Polizas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Roles_Usuarios_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Servicios_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Tasadores_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Valores_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Valores_Tenencias_Tipos_Instrumentos_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Zonas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Zonas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Zonas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Zonas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Zonas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tipos_Zonas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Topografias_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Topografias_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Topografias_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Topografias_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Topografias_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Topografias_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Unidades_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Unidades_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Unidades_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Unidades_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Unidades_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Unidades_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usos_Suelos_Actual_Entornos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usos_Suelos_Actual_Entornos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usos_Suelos_Actual_Entornos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usos_Suelos_Actual_Entornos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usos_Suelos_Actual_Entornos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usos_Suelos_Actual_Entornos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Actualiza_Conexion TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Actualiza_Intentos TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Consulta_Intentos TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Validar TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Validar_Acceso TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Usuarios_Validar_Acceso_Codigo TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Ventanas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Ventanas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Ventanas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Ventanas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Ventanas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Ventanas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Verjas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Verjas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Verjas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Verjas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Verjas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Verjas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Vias_Accesos_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Vias_Accesos_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Vias_Accesos_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Vias_Accesos_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Vias_Accesos_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Vias_Accesos_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Voltajes_Instalaciones_Electricas_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Voltajes_Instalaciones_Electricas_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Voltajes_Instalaciones_Electricas_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Voltajes_Instalaciones_Electricas_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Voltajes_Instalaciones_Electricas_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Voltajes_Instalaciones_Electricas_Total_Filas TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Actualiza TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Consulta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Consulta_Detalle TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Elimina TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Inserta TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Zonas_Tasadores_Total_Filas TO RAP_AccesoSIGANEM
GO



/*PERMISOS FNs */

GRANT EXECUTE ON Garantias_Reales_Id_Garantia_Lista TO RAP_AccesoSIGANEM
GO
GRANT EXECUTE ON Tramas_Obtener_Numericos TO RAP_AccesoSIGANEM
GO


/*PERMISOS FNs TABLA */

GRANT SELECT ON Garantias_Reales_Id_Garantia_Consulta TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Garantias_Reales_Id_Garantia_Filtra TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Garantias_Reales_Id_Garantia_Valida TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Garantias_Valores_Id_Garantia_Consulta TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Garantias_Valores_Id_Garantia_Filtra TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Garantias_Valores_Id_Garantia_Valida TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Operaciones_Id_Operacion_Consulta TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Operaciones_Id_Operacion_Filtra TO RAP_AccesoSIGANEM
GO
GRANT SELECT ON Operaciones_Id_Operacion_Valida TO RAP_AccesoSIGANEM
GO



