--ESCENARIO CP02

INSERT [dbo].[GARANTIAS_FIDEICOMETIDAS] (
[Id_Fideicomiso], [Id_Tipo_Garantia], [Id_Garantia_Real], [Id_Garantia_Valor], [Id_Dueno],   [Nombre_Dueno],           [Id_Tipo_Moneda_Valor_Nominal], [Valor_Nominal],               [Monto_Mitigador],            [Porcentaje_Aceptacion_No_Terreno_SUGEF], [Porcentaje_Aceptacion_Terreno_SUGEF], [Porcentaje_Aceptacion_SUGEF], [Porcentaje_Aceptacion_BCR], [Id_Tipo_Mitigador_Riesgo], [Id_Tipo_Documento_Legal], [Id_Tipo_Indicador_Inscripcion], [Fecha_Presentacion], [Id_Formato_Identificacion_Vehiculo], [Ind_Deudor_Habita], [Ind_Estado_Registro], [Ind_Metodo_Insercion], [Fecha_Ingreso],                              [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion], [Ind_Accion_Registro]) VALUES (
1380,             4,                  NULL,               1277,                N'401640901', N'Gonzalo Brenes Barva',  3,                              CAST(1.00 AS Numeric(24, 2)),  CAST(2.00 AS Numeric(24, 2)), NULL,                                     CAST(2.00 AS Decimal(5, 2)),           NULL,                          CAST(1.00 AS Numeric(5, 2)), 26,                         1,                         1,                               NULL,                 NULL,                                 NULL,                1,                     N'MANTENIMIENTO',       CAST(N'2016-04-13 15:40:31.530' AS DateTime), N'114000728',          NULL,                        NULL,                              N'I')


INSERT [dbo].[GARANTIAS_FIDEICOMETIDAS] (
[Id_Fideicomiso], [Id_Tipo_Garantia], [Id_Garantia_Real], [Id_Garantia_Valor], [Id_Dueno],   [Nombre_Dueno],           [Id_Tipo_Moneda_Valor_Nominal], [Valor_Nominal],               [Monto_Mitigador],            [Porcentaje_Aceptacion_No_Terreno_SUGEF], [Porcentaje_Aceptacion_Terreno_SUGEF], [Porcentaje_Aceptacion_SUGEF], [Porcentaje_Aceptacion_BCR], [Id_Tipo_Mitigador_Riesgo], [Id_Tipo_Documento_Legal], [Id_Tipo_Indicador_Inscripcion], [Fecha_Presentacion], [Id_Formato_Identificacion_Vehiculo], [Ind_Deudor_Habita], [Ind_Estado_Registro], [Ind_Metodo_Insercion], [Fecha_Ingreso],                              [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion], [Ind_Accion_Registro]) VALUES (
1381,             4,                  NULL,               1286,                N'401640902', N'Roger Brenes Morera',   3,                              CAST(1.00 AS Numeric(24, 2)),  CAST(2.00 AS Numeric(24, 2)), NULL,                                     CAST(2.00 AS Decimal(5, 2)),           NULL,                          CAST(1.00 AS Numeric(5, 2)), 26,                         1,                         1,                               NULL,                 NULL,                                 NULL,                1,                     N'MANTENIMIENTO',       CAST(N'2016-04-13 15:40:31.530' AS DateTime), N'114000728',          NULL,                        NULL,                              N'I')


--ESCENARIO CP03

INSERT [dbo].[GARANTIAS_FIDEICOMETIDAS] (
[Id_Fideicomiso], [Id_Tipo_Garantia], [Id_Garantia_Real], [Id_Garantia_Valor], [Id_Dueno],   [Nombre_Dueno],           [Id_Tipo_Moneda_Valor_Nominal], [Valor_Nominal],               [Monto_Mitigador],            [Porcentaje_Aceptacion_No_Terreno_SUGEF], [Porcentaje_Aceptacion_Terreno_SUGEF], [Porcentaje_Aceptacion_SUGEF], [Porcentaje_Aceptacion_BCR], [Id_Tipo_Mitigador_Riesgo], [Id_Tipo_Documento_Legal], [Id_Tipo_Indicador_Inscripcion], [Fecha_Presentacion], [Id_Formato_Identificacion_Vehiculo], [Ind_Deudor_Habita], [Ind_Estado_Registro], [Ind_Metodo_Insercion], [Fecha_Ingreso],                              [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion], [Ind_Accion_Registro]) VALUES (
1382,             4,                  NULL,               1293,                N'401640903', N'Rafael Brenes Barva',   3,                              CAST(1.00 AS Numeric(24, 2)),  CAST(2.00 AS Numeric(24, 2)), NULL,                                     CAST(2.00 AS Decimal(5, 2)),           NULL,                          CAST(1.00 AS Numeric(5, 2)), 13,                         1,                         1,                               NULL,                 NULL,                                 NULL,                1,                     N'MANTENIMIENTO',       CAST(N'2016-04-13 15:40:31.530' AS DateTime), N'114000728',          NULL,                        NULL,                              N'I')


INSERT [dbo].[GARANTIAS_FIDEICOMETIDAS] (
[Id_Fideicomiso], [Id_Tipo_Garantia], [Id_Garantia_Real], [Id_Garantia_Valor], [Id_Dueno],   [Nombre_Dueno],           [Id_Tipo_Moneda_Valor_Nominal], [Valor_Nominal],               [Monto_Mitigador],            [Porcentaje_Aceptacion_No_Terreno_SUGEF], [Porcentaje_Aceptacion_Terreno_SUGEF], [Porcentaje_Aceptacion_SUGEF], [Porcentaje_Aceptacion_BCR], [Id_Tipo_Mitigador_Riesgo], [Id_Tipo_Documento_Legal], [Id_Tipo_Indicador_Inscripcion], [Fecha_Presentacion], [Id_Formato_Identificacion_Vehiculo], [Ind_Deudor_Habita], [Ind_Estado_Registro], [Ind_Metodo_Insercion], [Fecha_Ingreso],                              [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion], [Ind_Accion_Registro]) VALUES (
1383,             4,                  NULL,               1250,                N'401640904', N'Gerardo Brenes Morera', 3,                              CAST(1.00 AS Numeric(24, 2)),  CAST(2.00 AS Numeric(24, 2)), NULL,                                     CAST(2.00 AS Decimal(5, 2)),           NULL,                          CAST(1.00 AS Numeric(5, 2)), 13,                         1,                         1,                               NULL,                 NULL,                                 NULL,                1,                     N'MANTENIMIENTO',       CAST(N'2016-04-13 15:40:31.530' AS DateTime), N'114000728',          NULL,                        NULL,                              N'I')

