USE [USSIGANEM]
GO


SET IDENTITY_INSERT dbo.TIPOS_GARANTIAS ON

INSERT INTO dbo.TIPOS_GARANTIAS (Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(11,10,'Garantía Fideicomiso',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(12,99,'Garantía Aval',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		
		
) AS TIPOS_GARANTIAS (Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM TIPOS_GARANTIAS

SET IDENTITY_INSERT dbo.TIPOS_GARANTIAS OFF



/****************************************************************************************************************************************************/


SET IDENTITY_INSERT dbo.TRAMAS ON

INSERT INTO dbo.TRAMAS (Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(27,1,11,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(28,2,11,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(29,1,11,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(30,2,11,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(31,1,11,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(32,2,11,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(33,1,12,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(34,2,12,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(35,1,12,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(36,2,12,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(37,1,12,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(38,2,12,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')

		
) AS TRAMAS (Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM TRAMAS

SET IDENTITY_INSERT dbo.TRAMAS OFF

GO

DECLARE 
	@Id_Tipo_Mitigador_Riesgo INT,
	@Id_Tipo_Garantia INT,
	@Id_Categoria_Calificacion INT

SELECT 
	@Id_Tipo_Mitigador_Riesgo = Id_Tipo_Mitigador_Riesgo 
FROM 
	dbo.TIPOS_MITIGADORES_RIESGOS TM 
WHERE 
	Cod_Tipo_Mitigador_Riesgo = 29


SELECT 
	@Id_Tipo_Garantia = Id_Tipo_Garantia
FROM 
	dbo.TIPOS_GARANTIAS 
WHERE
	Cod_Tipo_Garantia = 11

SELECT 
	@Id_Categoria_Calificacion = Id_Categoria_Calificacion
FROM 
	dbo.CATEGORIAS_CALIFICACIONES
WHERE 
	Cod_Categoria_Calificacion = 2
	
INSERT INTO dbo.CATEGORIAS_CALIFICACIONES_TIPOS_MITIGADORES_RIESGOS
(Id_Categoria_Calificacion,Id_Tipo_Mitigador_Riesgo,Id_Tipo_Garantia,Porc_Aceptacion_Calificacion_Riesgo,Ind_Metodo_Insercion,Fecha_Ingreso,Cod_Usuario_Ingreso)
VALUES (@Id_Categoria_Calificacion,@Id_Tipo_Mitigador_Riesgo,@Id_Tipo_Garantia,99,'MANTENIMIENTO',GETDATE(),'999999999')



/*GATANTÍAS AVALES RELACIONADAS*/
INSERT INTO ADMINISTRACIONES_CONTENIDOS(Cod_Pantalla, Nombre_Propiedad, Des_Columna, Tab, Ind_Requerido, Ind_Modificar, Ind_Visible, Valor_Defecto,Tipo_Contenido,Valor_Maximo,
Css_Tipo,Metodo_Servicio_Web,Grupo_Validacion,Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

/*INSERCION NUEVOS CAMPOS ADMINISTRACIÓN_CONTENIDOS SECCION GENERAL GARANTIAS AVALES*/
SELECT 24,'IdTipoAval','Tipo Aval', 'Avales', 1, 0, 1,NULL,'DROPDOWNLIST', NULL,
	   'mainTableBoxesCss','TipoAvalLista',NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'NAval','N° Aval', 'Avales', 1, 0, 1,NULL,'TEXTBOX', NULL,
	   'mainTableBoxesCss',NULL,'ValidacionAvalesGeneral', 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'IdTipoIdentificacionAvalista','Tipo Identificación Avalista', 'Avales', 0, 0, 1,NULL,'TEXTBOX', NULL,
	   'mainTableBoxesCss',NULL,NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
	   UNION ALL
SELECT 24,'IdentificaciónAvalista','Identificación Avalista', 'Avales', 0, 0, 1,NULL,'TEXTBOX', NULL,
	   'mainTableBoxesCss',NULL,NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
	   UNION ALL
SELECT 24,'MontoAvalado','Monto Avalado', 'Avales', 0, 0, 1,NULL,'TEXTBOX', NULL,
	   'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
	   UNION ALL
SELECT 24,'IdClaseGarantiaPrt17','Clase Garantía', 'Avales', 0, 0, 1,'20 - Seguridades','DROPDOWNLIST', NULL,
		'mainTableBoxesCss','ClasesGarantiasPRT17Lista', NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'IdTenenciaPrt15','Código Tenencia', 'Avales', 0, 0, 1,'37 - Aval Garantía FINADE','DROPDOWNLIST', NULL,
		'mainTableBoxesCss','TenenciasPRT15Lista', NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'IdGradoGravamen','Grado Gravamen', 'Avales', 0, 0, 1,'01 - Primer Grado','DROPDOWNLIST', NULL,
		'mainTableBoxesCss','GradosGravamenesLista', NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'IdTipoMonedaGradoGravamen','Tipo Moneda Monto Gravamen', 'Avales', 0, 0, 1,NULL,'DROPDOWNLIST', NULL,
		'mainTableBoxesCss','MonedasLista', NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'IdTipoMitigadorRiesgo','Tipo Mitigador Riesgo', 'Avales', 0, 0, 1,'0 – No Mitigador','DROPDOWNLIST', NULL,
	'mainTableBoxesCss','TiposMitigadoresRiesgosLista', NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'IdTipoDocumentoLegal','Tipo Documento Legal', 'Avales', 0, 0, 1,'29 - Fianzas y avales','DROPDOWNLIST', NULL,
	'mainTableBoxesCss','TiposDocumentosLegalesLista', NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
GO
/*GATANTÍAS AVALES RELACIONADAS*/
INSERT INTO ADMINISTRACIONES_CONTENIDOS(Cod_Pantalla, Nombre_Propiedad, Des_Columna, Tab, Ind_Requerido, Ind_Modificar, Ind_Visible, Valor_Defecto,Mascara,Valor_Mascara,Tipo_Contenido,Valor_Maximo,
Css_Tipo,Metodo_Servicio_Web,Grupo_Validacion,Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

SELECT 24,'MontoGradoGravamen','Monto Grado Gravamen', 'Avales', 1, 1, 1,NULL,1,'99,999,999,999,999,999,999.99', 'TEXTBOX', NULL,
'mainTableBoxesCss',NULL, 'ValidacionAvalesAdicional', 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'MontoMitigador','Monto Mitigador', 'Avales', 0, 1, 1,NULL,1,'99,999,999,999,999,999,999.99','TEXTBOX', NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'MontoMitigadorCalculado','Monto Mitigador Calculado', 'Avales', 0, 0, 1,NULL,1,'9,999,999,999,999,999,999,999.99','TEXTBOX', NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'PorcentajeAceptBCR','Porcentaje Aceptación BCR', 'Avales', 1, 1, 1,0,1,'999.99%','TEXTBOX', NULL,
	'mainTableBoxesCss',NULL, 'ValidacionAvalesAdicional', 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'PorcentajeAceptSugef','Porcentaje Aceptación SUGEF', 'Avales', 0, 0, 1,0,1,'999.99%','TEXTBOX', NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
	UNION ALL
SELECT 24,'PorcentajeResponSugef','Porcentaje Responsabilidad SUGEF', 'Avales', 0, 0, 1,NULL,1,'999.99%','TEXTBOX', NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
	UNION ALL
SELECT 24,'PorcentajeResponLegal','Porcentaje Responsabilidad Legal', 'Avales', 0, 0, 1,NULL,1,'999.99%','TEXTBOX', NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'

/*GATANTÍAS AVALES FECHAS*/
INSERT INTO ADMINISTRACIONES_CONTENIDOS(Cod_Pantalla, Nombre_Propiedad, Des_Columna, Tab, Ind_Requerido, Ind_Modificar, Ind_Visible, Valor_Defecto, Mascara, Tipo_Contenido,Valor_Minimo,Valor_Maximo,
Css_Tipo,Metodo_Servicio_Web,Grupo_Validacion,Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT 24,'FechaPrescripcionGarantia','Fecha Prescripción Garantía', 'Avales', 0, 0, 1,NULL,2,'CALENDAREXTENDER','DATETIME', NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'FechaConstitucionGarantia','Fecha Constitución Garantía', 'Avales', 0, 0, 1,NULL,2,'CALENDAREXTENDER', 'DATETIME',NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'
UNION ALL
SELECT 24,'FechaVencimientoGarantia','Fecha Vencimiento Garantía', 'Avales', 0, 0, 1,NULL,2,'CALENDAREXTENDER', 'DATETIME',NULL,
	'mainTableBoxesCss',NULL, NULL, 'MANTENIMIENTO',GETDATE(),'999999999'



INSERT INTO [dbo].[ADMINISTRACIONES_CONTENIDOS]
 (
	[Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara],
  [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden],
  [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]
 )

     VALUES

(24, 'IdFideicomisoBCR', NULL, 'Id Fideicomiso BCR', 'Fideico', NULL, 1, 1, 1, 0, NULL, 14, NULL, NULL, 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'TipoMonedaValorNominal', NULL, 'Tipo Moneda Valor Nominal', 'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, NULL, NULL, 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'ValorNominal', NULL, 'Valor Nominal', 'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, NULL, NULL, 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'ClaseGarantia', NULL, 'Clase Garantía', 'Fideico', NULL, 0, 0, 1, 1, '20 - Seguridades', NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'ClasesGarantiasPRT17Lista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'IndInscripcion', NULL, 'Indicador Inscripción', 'Fideico', NULL, 0, 0, 1, 1, '0, - No Aplica', NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'TipoIndicadorInscripcionLista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'CodigoTenencia', NULL, 'Código Tenencia', 'Fideico', NULL, 0, 0, 1, 1, '11 - Fideicomiso de Garantía', NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'TenenciasPRT15Lista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'TipoMitigadorRiesgo', NULL, 'Tipo Mitigador Riesgo', 'Fideico', NULL, 0, 0, 1, 1, '24 - Fideicomiso de garantías', NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'TiposMitigadoresRiesgosLista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'GradoGravamen', NULL, 'Grado Gravamen', 'Fideico', NULL, 0, 0, 1, 1, '1, - 1, grado', NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'GradosGravamenesLista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'TipoDocumentoLegal', NULL, 'Tipo Documento Legal', 'Fideico', NULL, 0, 1, 1, 0, NULL, NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'TiposDocumentosLegalesLista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'TipoMonedaMontoGraven', NULL, 'Tipo Moneda Monto Gravamen', 'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, NULL, NULL, 
 'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', 'MonedasLista', NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'MontoMitigador', NULL, 'Monto Mitigador', 'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, 1, '9999999999999999999999.99', 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'MontoGradoGravamen', NULL, 'Monto Grado Gravamen', 'Fideico', NULL, 1, 1, 1, NULL, 0, NULL, 1, '99999999999999999999.99', 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'PorcentajeResponsabilidadSUGEF', NULL, 'Porcentaje Responsabilidad SUGEF', 'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, 1, '999.99%', 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL),

(24, 'FechaPrescripcionGarantia', NULL, 'Fecha Prescripción Garantía', 'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, 1, 'DD/MM/AAAA', 
 'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, 'mainTableBoxesCss', NULL, NULL, NULL, NULL, 
 'MANTENIMIENTO', GETDATE(), '999999999', NULL, NULL)
