USE [USSIGANEM]
GO


SET IDENTITY_INSERT dbo.TIPOS_GARANTIAS ON

INSERT INTO dbo.TIPOS_GARANTIAS (Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(11,10,'Garantía Fideicomiso',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(12,99,'Garantía Aval',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		
		
) AS TIPOS_GARANTIAS (Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM TIPOS_GARANTIAS

SET IDENTITY_INSERT dbo.TIPOS_GARANTIAS OFF



/****************************************************************************************************************************************************/


SET IDENTITY_INSERT dbo.TRAMAS ON

INSERT INTO dbo.TRAMAS (Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(27,1,11,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(28,2,11,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(29,1,11,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(30,2,11,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(31,1,11,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(32,2,11,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(33,1,12,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(34,2,12,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(35,1,12,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(36,2,12,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(37,1,12,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(38,2,12,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')

		
) AS TRAMAS (Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM TRAMAS

SET IDENTITY_INSERT dbo.TRAMAS OFF

GO

DECLARE 
	@Id_Tipo_Mitigador_Riesgo INT,
	@Id_Tipo_Garantia INT,
	@Id_Categoria_Calificacion INT

SELECT 
	@Id_Tipo_Mitigador_Riesgo = Id_Tipo_Mitigador_Riesgo 
FROM 
	dbo.TIPOS_MITIGADORES_RIESGOS TM 
WHERE 
	Cod_Tipo_Mitigador_Riesgo = 29


SELECT 
	@Id_Tipo_Garantia = Id_Tipo_Garantia
FROM 
	dbo.TIPOS_GARANTIAS 
WHERE
	Cod_Tipo_Garantia = 11

SELECT 
	@Id_Categoria_Calificacion = Id_Categoria_Calificacion
FROM 
	dbo.CATEGORIAS_CALIFICACIONES
WHERE 
	Cod_Categoria_Calificacion = 2
	
INSERT INTO dbo.CATEGORIAS_CALIFICACIONES_TIPOS_MITIGADORES_RIESGOS
(Id_Categoria_Calificacion,Id_Tipo_Mitigador_Riesgo,Id_Tipo_Garantia,Porc_Aceptacion_Calificacion_Riesgo,Ind_Metodo_Insercion,Fecha_Ingreso,Cod_Usuario_Ingreso)
VALUES (@Id_Categoria_Calificacion,@Id_Tipo_Mitigador_Riesgo,@Id_Tipo_Garantia,99,'MANTENIMIENTO',GETDATE(),'999999999')



/*INSERCION NUEVOS CAMPOS ADMINISTRACIÓN_CONTENIDOS SECCION GENERAL GARANTIAS AVALES Y GARANTIAS FIEDICOMISO*/

INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdTipoAval', NULL, N'Tipo Aval', N'Avales', NULL, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TipoAvalLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 12:26:31.770' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'NAval', NULL, N'N° Aval', N'Avales', NULL, 1, 1, 1, NULL, NULL, NULL, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, N'ValidacionAvalesGeneral', NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 12:26:31.770' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdTipoIdentificacionAvalista', NULL, N'Tipo Identificación Avalista', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdentificacionAvalista', NULL, N'Identificación Avalista', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'MontoAvalado', NULL, N'Monto Avalado', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdClaseGarantiaPrt17', NULL, N'Clase Garantía', N'Avales', NULL, 0, 0, 1, NULL, N'20 - Seguridades', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'ClasesGarantiasPRT17Lista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdTenenciaPrt15', NULL, N'Código Tenencia', N'Avales', NULL, 0, 0, 1, NULL, N'37 - Aval Garantía FINADE', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TenenciasPRT15Lista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdGradoGravamen', NULL, N'Grado Gravamen', N'Avales', NULL, 0, 0, 1, NULL, N'01 - Primer Grado', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'GradosGravamenesLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdTipoMonedaGradoGravamen', NULL, N'Tipo Moneda Monto Gravamen', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'MonedasLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'FechaConstitucionGarantia', NULL, N'Fecha Constitución Garantía', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, N'2', NULL, N'CALENDAREXTENDER', N'DATETIME', NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'FechaVencimientoGarantia', NULL, N'Fecha Vencimiento Garantía', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, N'2', NULL, N'CALENDAREXTENDER', N'DATETIME', NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'FechaPrescripcionGarantia', NULL, N'Fecha Prescripción Garantía', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, N'2', NULL, N'CALENDAREXTENDER', N'DATETIME', NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdTipoMitigadorRiesgo', NULL, N'Tipo Mitigador Riesgo', N'Avales', NULL, 0, 0, 1, NULL, N'0 – No Mitigador', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TiposMitigadoresRiesgosLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdTipoDocumentoLegal', NULL, N'Tipo Documento Legal', N'Avales', NULL, 0, 0, 1, NULL, N'29 - Fianzas y avales', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TiposDocumentosLegalesLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.860' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'MontoGradoGravamen', NULL, N'Monto Grado Gravamen', N'Avales', NULL, 1, 1, 1, NULL, NULL, NULL, N'1', N'99,999,999,999,999,999,999.99', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, N'ValidacionAvalesAdicional', NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'MontoMitigador', NULL, N'Monto Mitigador', N'Avales', NULL, 0, 1, 1, NULL, NULL, NULL, N'1', N'99,999,999,999,999,999,999.99', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'MontoMitigadorCalculado', NULL, N'Monto Mitigador Calculado', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, N'1', N'9,999,999,999,999,999,999,999.99', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'PorcentajeAceptBCR', NULL, N'Porcentaje Aceptación BCR', N'Avales', NULL, 1, 1, 1, NULL, N'0', NULL, N'1', N'999.99%', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, N'ValidacionAvalesAdicional', NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'PorcentajeAceptSugef', NULL, N'Porcentaje Aceptación SUGEF', N'Avales', NULL, 0, 0, 1, NULL, N'0', NULL, N'1', N'999.99%', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'PorcentajeResponSugef', NULL, N'Porcentaje Responsabilidad SUGEF', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, N'1', N'999.99%', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'PorcentajeResponLegal', NULL, N'Porcentaje Responsabilidad Legal', N'Avales', NULL, 0, 0, 1, NULL, NULL, NULL, N'1', N'999.99%', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-21 14:57:28.880' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IdFideicomisoBCR', NULL, N'Id Fideicomiso BCR', N'Fideico', NULL, 1, 1, 1, 0, NULL, 14, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'TipoMonedaValorNominal', NULL, N'Tipo Moneda Valor Nominal', N'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'ValorNominal', NULL, N'Valor Nominal', N'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, NULL, NULL, N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'ClaseGarantia', NULL, N'Clase Garantía', N'Fideico', NULL, 0, 0, 1, 1, N'20 - Seguridades', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'ClasesGarantiasPRT17Lista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'IndInscripcion', NULL, N'Indicador Inscripción', N'Fideico', NULL, 0, 0, 1, 1, N'0 - No Aplica', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TipoIndicadorInscripcionLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'CodigoTenencia', NULL, N'Código Tenencia', N'Fideico', NULL, 0, 0, 1, 1, N'11 - Fideicomiso de Garantía', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TenenciasPRT15Lista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'TipoMitigadorRiesgo', NULL, N'Tipo Mitigador Riesgo', N'Fideico', NULL, 0, 0, 1, 1, N'24 - Fideicomiso de garantías', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TiposMitigadoresRiesgosLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'GradoGravamen', NULL, N'Grado Gravamen', N'Fideico', NULL, 0, 0, 1, 1, N'1 - 1 grado', NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'GradosGravamenesLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'TipoDocumentoLegal', NULL, N'Tipo Documento Legal', N'Fideico', NULL, 0, 1, 1, 0, NULL, NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'TiposDocumentosLegalesLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'TipoMonedaMontoGraven', NULL, N'Tipo Moneda Monto Gravamen', N'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, NULL, NULL, N'DROPDOWNLIST', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', N'MonedasLista', NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'MontoMitigador', NULL, N'Monto Mitigador', N'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, N'1', N'9,999,999,999,999,999,999,999.99', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'MontoGradoGravamen', NULL, N'Monto Grado Gravamen', N'Fideico', NULL, 1, 1, 1, NULL, N'0', NULL, N'1', N'99,999,999,999,999,999,999.99', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'PorcentajeResponsabilidadSUGEF', NULL, N'Porcentaje Responsabilidad SUGEF', N'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, N'1', N'999.99%', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMIENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO
INSERT [dbo].[ADMINISTRACIONES_CONTENIDOS] ([Cod_Pantalla], [Nombre_Propiedad], [Nombre_Columna], [Des_Columna], [Tab], [Nombre_Tab], [Ind_Requerido], [Ind_Modificar], [Ind_Visible], [Ind_Valor_Defecto], [Valor_Defecto], [Longitud_Maxima], [Mascara], [Valor_Mascara], [Tipo_Contenido], [Valor_Minimo], [Valor_Maximo], [Nombre_Servicio_Web], [Valor_Servicio_Web], [Texto_Servicio_Web], [Tipo_Objeto], [Css_Tipo], [Metodo_Servicio_Web], [Grupo_Validacion], [Nombre_Propiedad_Asociada], [Orden], [Ind_Metodo_Insercion], [Fecha_Ingreso], [Cod_Usuario_Ingreso], [Fecha_Ultima_Modificacion], [Cod_Usuario_Ultima_Modificacion]) VALUES (24, N'FechaPrescripcionGarantia', NULL, N'Fecha Prescripción Garantía', N'Fideico', NULL, 0, 0, 1, 0, NULL, NULL, N'1', N'DD/MM/AAAA', N'TEXTBOX', NULL, NULL, NULL, NULL, NULL, NULL, N'mainTableBoxesCss', NULL, NULL, NULL, NULL, N'MANTENIMENTO', CAST(N'2016-06-23 00:00:00.000' AS DateTime), N'999999999', NULL, NULL)
GO





 SET IDENTITY_INSERT dbo.PROCESOS ON

INSERT INTO dbo.PROCESOS (Id_Proceso, Cod_Proceso, Des_Proceso, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Proceso, Cod_Proceso, Des_Proceso, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(11,11,'Coloniza Valor Mercado','MANTENIMIENTO', CAST('19000101' AS DateTime), N'999999999')
		,(12,12,'Actualiza Valor Nominal','MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(13,13,'Actualiza Porcentajes de Aceptación Fideicometida','MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(14,14,'Calcula Monto Mitigador Fideicometida','MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(15,15,'Coloniza Montos Prioridades de Garantías','MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		
		
) AS PROCESOS (Id_Proceso, Cod_Proceso, Des_Proceso, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Proceso, Cod_Proceso, Des_Proceso, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM PROCESOS

SET IDENTITY_INSERT dbo.PROCESOS OFF

GO


UPDATE dbo.PROCESOS
SET Des_Proceso = 'Actualiza Porcentajes de Aceptación de relaciones'
WHERE Id_Proceso = 8
GO


UPDATE dbo.PROCESOS
SET Des_Proceso = 'Calcula Monto Mitigador de relaciones'
WHERE Id_Proceso = 9
GO

UPDATE dbo.GARANTIAS_OPERACIONES
SET Id_Tipo_Garantia = 8
WHERE Id_Tipo_Garantia = 11
AND Id_Fideicomiso IS NOT NULL
GO

UPDATE dbo.GARANTIAS_OPERACIONES
SET Id_Tipo_Garantia = 11
WHERE Id_Tipo_Garantia = 12
AND Id_Garantia_Aval IS NOT NULL
GO

UPDATE dbo.CATEGORIAS_CALIFICACIONES_TIPOS_MITIGADORES_RIESGOS 
SET Id_Tipo_Garantia = 8
WHERE Id_Tipo_Garantia = 11
GO

UPDATE dbo.CATEGORIAS_CALIFICACIONES_TIPOS_MITIGADORES_RIESGOS 
SET Id_Tipo_Garantia = 11
WHERE Id_Tipo_Garantia = 12
GO

UPDATE dbo.TRAMAS
SET Id_Tipo_Garantia = 8
WHERE Id_Tipo_Garantia = 11
GO 

UPDATE dbo.TRAMAS
SET Id_Tipo_Garantia = 11
WHERE Id_Tipo_Garantia = 12
GO


DELETE FROM dbo.TIPOS_GARANTIAS
WHERE Id_Tipo_Garantia = 12
GO

UPDATE dbo.TIPOS_GARANTIAS
SET Cod_Tipo_Garantia = 99,
	Des_Tipo_Garantia = 'Garantía Aval'
WHERE Id_Tipo_Garantia = 11
GO
