USE [SIGANEM]
GO


SET IDENTITY_INSERT dbo.TIPOS_GARANTIAS ON

INSERT INTO dbo.TIPOS_GARANTIAS (Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(11,10,'Garantía Fideicomiso',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(12,99,'Garantía Aval',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		
		
) AS TIPOS_GARANTIAS (Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Tipo_Garantia, Cod_Tipo_Garantia, Des_Tipo_Garantia, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM TIPOS_GARANTIAS

SET IDENTITY_INSERT dbo.TIPOS_GARANTIAS OFF



/****************************************************************************************************************************************************/


SET IDENTITY_INSERT dbo.TRAMAS ON

INSERT INTO dbo.TRAMAS (Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)
SELECT
	 Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso
FROM (
	VALUES 
		(27,1,11,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(28,2,11,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(29,1,11,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(30,2,11,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(31,1,11,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(32,2,11,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(33,1,12,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(34,2,12,'PRT15','CON','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON></PMO-RESPON><PCO-MONGAR></PCO-MONGAR><PCO-TENEN></PCO-TENEN><PCO-GRAVA></PCO-GRAVA><PFEPREGAR></PFEPREGAR><ACCION>CON</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(35,1,12,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(36,2,12,'PRT15','ADI','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>ADI</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(37,1,12,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT>@PCO-CONT@</PCO-CONT><PCO-OFIC>@PCO-OFIC@</PCO-OFIC><PCO-MONE>@PCO-MONE@</PCO-MONE><PCO-PROD>@PCO-PROD@</PCO-PROD><PNU-OPERA>@PNU-OPERA@</PNU-OPERA><PCO-CON></PCO-CON><PCO-OFI></PCO-OFI><PCO-MON></PCO-MON><PNU-CONT></PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')
		,(38,2,12,'PRT15','BOR','<TRAMAXML><HEADER><REGISTRO></REGISTRO><REFERENCIA>Transaccion evento pres</REFERENCIA><USUARIO>11000001</USUARIO><CANAL></CANAL><TRANS></TRANS><CODIGORESPUESTA></CODIGORESPUESTA><DESCRIPCION></DESCRIPCION><OFICINAORIGEN></OFICINAORIGEN><ESTACION></ESTACION><FECHAHORA></FECHAHORA></HEADER><PRT15><ISPEC>PRT15</ISPEC><PCO-CONT></PCO-CONT><PCO-OFIC></PCO-OFIC><PCO-MONE></PCO-MONE><PCO-PROD></PCO-PROD><PNU-OPERA></PNU-OPERA><PCO-CON>@PCO-CON@</PCO-CON><PCO-OFI>@PCO-OFI@</PCO-OFI><PCO-MON>@PCO-MON@</PCO-MON><PNU-CONT>@PNU-CONT@</PNU-CONT><PNU-IDENT>@PNU-IDENT@</PNU-IDENT><PCOTIPGAR>@PCOTIPGAR@</PCOTIPGAR><PMO-RESPON>@PMO-RESPON@</PMO-RESPON><PCO-MONGAR>@PCO-MONGAR@</PCO-MONGAR><PCO-TENEN>@PCO-TENEN@</PCO-TENEN><PCO-GRAVA>@PCO-GRAVA@</PCO-GRAVA><PFEPREGAR>@PFEPREGAR@</PFEPREGAR><ACCION>BOR</ACCION></PRT15></TRAMAXML>',N'MANTENIMIENTO',CAST('19000101' AS DateTime), N'999999999')

		
) AS TRAMAS (Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso)

EXCEPT 
	SELECT Id_Trama, Id_Tipo_Operacion, Id_Tipo_Garantia, Cod_Trama, Cod_Accion, Trama, Ind_Metodo_Insercion, Fecha_Ingreso, Cod_Usuario_Ingreso FROM TRAMAS

SET IDENTITY_INSERT dbo.TRAMAS OFF

GO

DECLARE 
	@Id_Tipo_Mitigador_Riesgo INT,
	@Id_Tipo_Garantia INT,
	@Id_Categoria_Calificacion INT

SELECT 
	@Id_Tipo_Mitigador_Riesgo = Id_Tipo_Mitigador_Riesgo 
FROM 
	dbo.TIPOS_MITIGADORES_RIESGOS TM 
WHERE 
	Cod_Tipo_Mitigador_Riesgo = 29


SELECT 
	@Id_Tipo_Garantia = Id_Tipo_Garantia
FROM 
	dbo.TIPOS_GARANTIAS 
WHERE
	Cod_Tipo_Garantia = 11

SELECT 
	@Id_Categoria_Calificacion = Id_Categoria_Calificacion
FROM 
	dbo.CATEGORIAS_CALIFICACIONES
WHERE 
	Cod_Categoria_Calificacion = 2
	
INSERT INTO dbo.CATEGORIAS_CALIFICACIONES_TIPOS_MITIGADORES_RIESGOS
(Id_Categoria_Calificacion,Id_Tipo_Mitigador_Riesgo,Id_Tipo_Garantia,Porc_Aceptacion_Calificacion_Riesgo,Ind_Metodo_Insercion,Fecha_Ingreso,Cod_Usuario_Ingreso)
VALUES (@Id_Categoria_Calificacion,@Id_Tipo_Mitigador_Riesgo,@Id_Tipo_Garantia,99,'MANTENIMIENTO',GETDATE(),'999999999')
