USE [USSIGANEM]
GO

/* GARANTIAS OPERACIONES */

ALTER TABLE [dbo].[GARANTIAS_OPERACIONES] ADD Monto_Grado_Gravamen_Original NUMERIC(22, 2) NULL
GO

ALTER TABLE [dbo].[GARANTIAS_OPERACIONES] ADD Monto_Grado_Gravamen_Modificado NUMERIC(22, 2) NULL
GO

ALTER TABLE [dbo].[GARANTIAS_OPERACIONES] ADD Ind_Monto_Grado_Gravamen_Modificado BIT NULL
GO


